name: CI

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2022]
        config: [Debug, Release]
        platform: [x64]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      run: |
        cmake -B build -A ${{ matrix.platform }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.config }} --parallel